---
- hosts: "{{ host_gp }}"
  gather_facts: yes
  become: true

  # vars:
  #   ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'smartmontools' ]
      tags: [ textfile ]

    - name: Service List
      service_facts:
      tags: [ systemd,textfile ]

    - name: Stop node_exporter
      service:
        name: node_exporter.service
        state: stopped
        enabled: true
      when: ansible_facts.services['node_exporter.service'] is defined      
      tags: [ systemd,textfile ]


    - name: Transfer the smartmon.sh script
      copy: src=smartmon.sh dest=/home/smartmon.sh mode=0755
      tags: [ textfile ]    

    - name: "Run a smartmon.sh on remote host"
      shell: "bash /home/smartmon.sh"
      tags: [ textfile ]

    - name: Creates directory
      file:
        path: /var/lib/node_exporter/textfile_collector
        state: directory
        owner: root
        group: root
        recurse: yes      
      tags: [ textfile ] 

    - name: Transfer the node-exporter.sh script to install node_exporter
      copy: src=node-exporter.sh dest=/home/node-exporter.sh mode=0755
      tags: [ systemd,textfile ]

    - name: "Run a node-exporter.sh on remote host"
      shell: "bash /home/node-exporter.sh"
      tags: [ systemd,textfile ]

    - name: Transfer the create_service_node.sh script
      copy: src=create_service_node.sh dest=/home/create_service_node.sh mode=0755
      tags: [ systemd ]

    - name: "Run create_service_node.sh on remote host"
      shell: "bash /home/create_service_node.sh"
      tags: [ systemd ]
      

    - name: Transfer the create_service_node_2.sh script
      copy: src=create_service_node_2.sh dest=/home/create_service_node_2.sh mode=0755
      tags: [ textfile ]

    - name: "Run create_service_node_2.sh on remote host"
      shell: "bash /home/create_service_node_2.sh"
      tags: [ textfile ]

    - name: set cron textfile_collector
      ansible.builtin.cron:
        name: "textfile_collector"
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"        
        job: "/usr/local/bin/smartmon.sh > /var/lib/node_exporter/textfile_collector/smart_metrics.prom"
      tags: [ textfile ]  

    - name: node_exporter.service restart
      ansible.builtin.service:
        name: node_exporter.service
        state: restarted
        enabled: true
      tags: [ systemd,textfile ]  
