---
- hosts: "{{ host_gp }}"
  gather_facts: yes
  become: true

  # vars:
  #   ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'smartmontools' ]
      tags: [ systemd,textfile ]

    - name: Service List
      service_facts:
      tags: [ systemd,textfile ]

    - name: Stop node_exporter
      service:
        name: node_exporter.service
        state: stopped
        enabled: true
      when: ansible_facts.services['node_exporter.service'] is defined      
      tags: [ systemd,textfile ]

    - name: Transfer the smartmon.sh script
      copy: src=smartmon.sh dest=/home/smartmon.sh mode=0755
      tags: [ systemd,textfile ]  

    - name: Transfer the node-exporter.sh script to install node_exporter
      copy: src=node-exporter.sh dest=/home/node-exporter.sh mode=0755
      tags: [ systemd,textfile ]

    - name: "Run a node-exporter.sh on remote host"
      shell: "bash /home/node-exporter.sh"
      tags: [ systemd,textfile ]
  
    - name: node_exporter.service start
      ansible.builtin.service:
        name: node_exporter.service
        state: started
        enabled: true
      tags: [ systemd,textfile ]
